packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - electron
  - electron-winstaller

patchedDependencies:
  '@sveltejs/kit': patches/@sveltejs__kit.patch
