/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "BlogApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "CloudflareAccountId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudflareApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubPersonalAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KwokPhoneNumber": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MichellePhoneNumber": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NotionApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NotionBlogDeployAuth": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NotionTodoRemindAuth": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StaticWebsite": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "TodoRemindApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TwilioAccountSid": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioPhoneNumber": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}