# used to pull private images from ghcr.io
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: example
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "Pandoks",
          "password": "${GithubPersonalAccessToken}"
        }
      }
    }

---
# allows the default service account for the example namespace to pull private images from ghcr.io by default
# without needing to specify the imagePullSecrets field in the pod spec
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: example
imagePullSecrets:
  - name: ghcr-auth

---
# used to terminate TLS at the ingress controller for the traffic flow: client -> cloudflare -- here -> k3s
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-tls
  namespace: example
type: kubernetes.io/tls
stringData:
  tls.crt: |
    ${HetznerOriginTlsCrt}
  tls.key: |
    ${HetznerOriginTlsKey}

---
# used to pull private images from ghcr.io
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: main
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "Pandoks",
          "password": "${GithubPersonalAccessToken}"
        }
      }
    }

---
# allows the default service account for the example namespace to pull private images from ghcr.io by default
# without needing to specify the imagePullSecrets field in the pod spec
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: main
imagePullSecrets:
  - name: ghcr-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: main-db-creds
  namespace: main
type: Opaque
stringData:
  SUPERUSER_PASSWORD: ${MainMainPostgresSuperuserPassword}
  ADMIN_PASSWORD: ${MainMainPostgresAdminPassword}
  CLIENT_PASSWORD: ${MainMainPostgresClientPassword}
  REPLICATION_PASSWORD: ${MainMainPostgresReplicationPassword}
  PATRONI_PASSWORD: ${MainMainPostgresPatroniPassword}
  BACKUP_S3_KEY: ${MainMainPostgresBackupS3Key}
  BACKUP_S3_KEY_SECRET: ${MainMainPostgresBackupS3KeySecret}
  users.toml: |
    [admin]
    password = "${MainMainPostgresPgdogAdminPassword}"

    [[users]]
    name = "client"
    database = "main"
    password = "${MainMainPostgresClientPassword}"
    pool_size = 20

---
apiVersion: v1
kind: Secret
metadata:
  name: valkey-main-creds
  namespace: main
type: Opaque
stringData:
  ADMIN_PASSWORD: ${ValkeyAdminPassword}
  CLIENT_PASSWORD: ${ValkeyClientPassword}

---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-main-creds
  namespace: main
type: Opaque
stringData:
  ADMIN_PASSWORD: ${ClickhouseAdminPassword}
  USER_PASSWORD: ${ClickhouseUserPassword}

---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-main-backup-creds
  namespace: main
type: Opaque
stringData:
  S3_KEY: ${ClickhouseS3Key}
  S3_KEY_SECRET: ${ClickhouseS3KeySecret}
