apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps
patches:
  - path: ../../../packages/postgres/kube/main/dev-patch.yaml
  - path: ../../../packages/valkey/kube/dev-patch.yaml
