apiVersion: v1
kind: Namespace
metadata:
  name: tailscale

---
# WARNING: make sure to match it with /infra/vps/cloud-config.yaml's tailscale bootstrap
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: kube-system
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  version: 1.92.5
  targetNamespace: tailscale
  valuesContent: |-
    apiServerProxyConfig:
      mode: "true"
  valuesSecrets:
    - name: tailscale
      keys:
        - tailscale-oauth
        - operator-config

---
# WARNING: make sure to match it with /infra/vps/cloud-config.yaml's tailscale bootstrap
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pandoks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: Pandoks@github
