apiVersion: v1
kind: Secret
metadata:
  name: example-tls
  namespace: example
type: kubernetes.io/tls
stringData:
  tls.crt: |
    ${sst.HetznerOriginTlsCrt}
  tls.key: |
    ${sst.HetznerOriginTlsKey}
