apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
type: Opaque
stringData:
  username: admin
  password: ${KubernetesGrafanaAdminPassword}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: ${StageName}-grafana
    tailscale.com/tags: tag:k8s,tag:${StageName}
spec:
  type: ClusterIP
