apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main-valkey-main-cluster
  namespace: kube-system
spec:
  chart: oci://${ImageRegistry}/charts/valkey
  version: 0.1.0 # renovate: datasource=docker packageName=pandoks/charts/valkey
  targetNamespace: &namespace main
  createNamespace: true
  failurePolicy: abort
  plainHTTP: ${IsLocal}
  set:
    name: main
    namespace: *namespace
    image: ${ValkeyImage}
    cluster.reconcilerImage: ${ValkeyReconcilerImage}
    cluster.masters: 1
    cluster.replicasPerMaster: 0
    credentials.secret: valkey-main-creds
