apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main-valkey-main-cluster
  namespace: kube-system
spec:
  chart: oci://ghcr.io/pandoks/charts/valkey
  version: 0.1.0
  targetNamespace: &namespace main
  createNamespace: true
  failurePolicy: abort
  set:
    name: main
    namespace: *namespace
    cluster.masters: 1
    cluster.replicasPerMaster: 0
    credentials.secret: valkey-main-creds
