/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly NOTION_API_KEY: string
  readonly NOTION_DATABASE_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}