{
 "title": "HAProxy / Cache / Compressor",
 "description": "HAProxy Cache / Compressor metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16208 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16208 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16478 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16478 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16489 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16489 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  }
 ]
}