/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/// <reference path="./.sst/platform/config.d.ts" />
declare module 'sst' {
  export interface Resource {}
}
export {};
