apiVersion: v1
kind: Secret
metadata:
  name: push-worker
  namespace: main
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${PushWorkerAwsAccessKeyId | quote}
  AWS_SECRET_ACCESS_KEY: ${PushWorkerAwsSecretAccessKey | quote}
  AWS_REGION: ${AwsRegion | quote}
  SQS_QUEUE_URL: ${PushQueueUrl | quote}
  FIREBASE_PROJECT_ID: ${FirebaseProjectId | quote}
  APNS_TEAM_ID: ${ApplePushNotificationTeamId | quote}
  APNS_KEY_ID: ${ApplePushNotificationKeyId | quote}
data:
  firebase-service-account.json: ${FirebaseServiceAccountJson | base64}
  AuthKey.p8: ${ApplePushNotificationApnsKey | base64}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-worker
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: push-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: push-worker
    spec:
      automountServiceAccountToken: false
      containers:
        - name: push-worker
          image: ${ImageRegistry}/push-worker:${PushWorkerImageTag}
          envFrom:
            - secretRef:
                name: push-worker
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/push/firebase-service-account.json
            - name: APNS_PRIVATE_KEY_PATH
              value: /var/run/secrets/push/AuthKey.p8
            - name: STAGE
              value: production
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: push-credentials
              mountPath: /var/run/secrets/push
              readOnly: true
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      volumes:
        - name: push-credentials
          secret:
            secretName: push-worker
            defaultMode: 0440
            items:
              - key: firebase-service-account.json
                path: firebase-service-account.json
              - key: AuthKey.p8
                path: AuthKey.p8
