apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main-postgres-main-cluster
  namespace: kube-system
spec:
  chart: oci://local-registry:5000/charts/postgres
  plainHTTP: true
  set:
    backup.image: local-registry:5000/pgbackrest:latest
    patroni.image: local-registry:5000/patroni:latest
    pgcat.image: local-registry:5000/pgcat:latest
