apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: &dbname main
  namespace: kube-system
spec:
  repo: oci://ghcr.io/pandoks/charts
  chart: postgres
  version: 0.1.0
  targetNamespace: &namespace main
  createNamespace: true
  set:
    db: *dbname
    namespace: *namespace
