apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main-postgres-main-cluster
  namespace: kube-system
spec:
  chart: oci://ghcr.io/pandoks/charts/postgres
  version: 0.1.0
  targetNamespace: &namespace main
  createNamespace: true
  set:
    db: main
    namespace: *namespace
