apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 80.14.0
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    kubeEtcd:
      enabled: true
      endpoints:
        - 172.30.0.4
        - 172.30.0.5
        - 172.30.0.6
      service:
        enabled: true
        port: 2381
        targetPort: 2381

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false

    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        retention: 7d

    grafana:
      persistence:
        enabled: false
      admin:
        existingSecret: grafana
        userKey: username
        passwordKey: password
