# Default values for postgres chart

db: example
namespace: example

backup:
  bucket: database
  encryptionKey: openssl-rand-hex-32
  path: /

s3:
  region: us-west-1
  endpoint: host.k3d.internal:4566
  tls: 'n'
  uriStyle: path

storage:
  className: local-path
  size: 1Gi

patroni:
  replicas: 3

pgcat:
  replicas: 3
