apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 80.14.4
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    # Hetzner control plane nodes on private network 10.0.1.0/24
    # IPs start at octet 10: control-plane-0=.10, control-plane-1=.11, etc. (/infra/vps/vps.ts)
    kubeEtcd:
      enabled: true
      endpoints:
        - 10.0.1.10
        # - 10.0.1.11  # uncomment when adding control-plane-1
        # - 10.0.1.12  # uncomment when adding control-plane-2
      service:
        enabled: true
        port: 2381
        targetPort: 2381

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false

    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        retention: 7d

    grafana:
      persistence:
        enabled: false
      admin:
        existingSecret: grafana
        userKey: username
        passwordKey: password
