name: example
namespace: example
image: ghcr.io/pandoks/valkey:latest@sha256:da0b51d171e30361a48f4d5cc03968d9994e74d5e1d811705c4904bc967cb100

credentials:
  secret: valkey-example-creds
  dataKeys:
    adminPassword: ADMIN_PASSWORD
    clientPassword: CLIENT_PASSWORD

cluster:
  masters: 1
  replicasPerMaster: 0
  reconcilerImage: ghcr.io/pandoks/valkey-reconciler:latest@sha256:be2e40024c2b906e0d963a39281eceffa8a48f16584e4c05b7564451dbdbe344

# No persistence by default
# options: rdb,aof | rdb | aof | ~
persistence: ~

resources:
  limits:
    cpu: 1000m
    memory: 1Gi

hooks:
  ttlSecondsAfterFinished: ~
  backoffLimit: ~
  restartPolicy: OnFailure
  hookDeletePolicy: before-hook-creation,hook-succeeded
