name: example
namespace: example
image: ghcr.io/pandoks/valkey:latest@sha256:a532e01001ff8ee607705764e7792a6263a84dc216202dec9458feca4419eed6

credentials:
  secret: valkey-example-creds
  dataKeys:
    adminPassword: ADMIN_PASSWORD
    clientPassword: CLIENT_PASSWORD

cluster:
  masters: 1
  replicasPerMaster: 0
  reconcilerImage: ghcr.io/pandoks/valkey-reconciler:latest@sha256:fca5d9ad3c68615da11ed3d01d9303de2b89ed550e80e17981603d1e5334121f

# No persistence by default
# options: rdb,aof | rdb | aof | ~
persistence: ~

resources:
  limits:
    cpu: 1000m
    memory: 1Gi

hooks:
  ttlSecondsAfterFinished: ~
  backoffLimit: ~
  restartPolicy: OnFailure
  hookDeletePolicy: before-hook-creation,hook-succeeded
