name: example
namespace: example
image: ghcr.io/pandoks/valkey:latest@sha256:6d449d693921a31dd80d6f4373a3ec9e7869a6f2ea8a1a6800cbca618ba56e9a

credentials:
  secret: valkey-example-creds
  dataKeys:
    adminPassword: ADMIN_PASSWORD
    clientPassword: CLIENT_PASSWORD

cluster:
  masters: 1
  replicasPerMaster: 0
  reconcilerImage: ghcr.io/pandoks/valkey-reconciler:latest@sha256:dcc64f2671be7921dc12a19b834c4c494963b8a90af3e58463578373446ce713

# No persistence by default
# options: rdb,aof | rdb | aof | ~
persistence: ~

resources:
  limits:
    cpu: 1000m
    memory: 1Gi

hooks:
  ttlSecondsAfterFinished: ~
  backoffLimit: ~
  restartPolicy: OnFailure
  hookDeletePolicy: before-hook-creation,hook-succeeded
