{
 "title": "HAProxy / Process Misc",
 "description": "HAProxy Process Misc metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Failed DNS resolutions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of failed DNS resolutions in current worker process since started"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{instance=\"$host\"}",
       "legendFormat": "Hard limit on the number of pipes for splicing, 0=unlimited"
      },
      {
       "expr": "rate(haproxy_process_pipes_used_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Used pipes"
      },
      {
       "expr": "rate(haproxy_process_pipes_free_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Free pipes"
      }
     ]
    },
    {
     "title": "Process - Listeners",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_listeners{instance=\"$host\"}",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{instance=\"$host\"}",
       "legendFormat": "Memory limit; 0=unset"
      },
      {
       "expr": "haproxy_process_pool_allocated_bytes{instance=\"$host\"}",
       "legendFormat": "Memory allocated in pools"
      },
      {
       "expr": "haproxy_process_pool_used_bytes{instance=\"$host\"}",
       "legendFormat": "Memory used in pools"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_pool_failures_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_jobs{instance=\"$host\"}",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "haproxy_process_unstoppable_jobs{instance=\"$host\"}",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      }
     ]
    },
    {
     "title": "Process - Configured Threads / Processes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{instance=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{instance=\"$host\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_dropped_logs_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "rate(haproxy_process_recv_logs_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_active_peers{instance=\"$host\"}",
       "legendFormat": "Active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{instance=\"$host\"}",
       "legendFormat": "Connected peers"
      }
     ]
    },
    {
     "title": "Process - Tasks / Runqueue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_tasks{instance=\"$host\"}",
       "legendFormat": "Total number of tasks in the current worker process (active + sleeping)"
      },
      {
       "expr": "haproxy_process_current_run_queue{instance=\"$host\"}",
       "legendFormat": "Total number of active tasks+tasklets in the current worker process"
      }
     ]
    },
    {
     "title": "Process - Idle / Stopping",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{instance=\"$host\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      },
      {
       "expr": "haproxy_process_stopping{instance=\"$host\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{instance=\"$host\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  }
 ]
}