{
 "title": "HAProxy / Process Traffic",
 "description": "HAProxy Process Traffic metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Process Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Connection rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_connection_rate{instance=\"$host\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{instance=\"$host\"}",
       "legendFormat": "Hard limit for ConnRate (global.maxconnrate)"
      }
     ]
    },
    {
     "title": "Process - Connections limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_connections{instance=\"$host\"}",
       "legendFormat": "Current number of connections on this worker process"
      },
      {
       "expr": "haproxy_process_hard_max_connections{instance=\"$host\"}",
       "legendFormat": "Hard limit on the number of per-process connections (imposed by Memmax_MB or ulimit -n)"
      }
     ]
    },
    {
     "title": "Process - Sessions limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_session_rate{instance=\"$host\"}",
       "legendFormat": "Highest SessRate reached on this worker process since started (in sessions per second)"
      },
      {
       "expr": "haproxy_process_limit_session_rate{instance=\"$host\"}",
       "legendFormat": "Hard limit for SessRate (global.maxsessrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Hard limit for SslRate (global.maxsslrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{instance=\"$host\"}",
       "legendFormat": "SSL endpoints"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{instance=\"$host\"}",
       "legendFormat": "Hard limit  SSL endpoints"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "SSL keys created on frontends"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "SSL keys created on backend"
      }
     ]
    },
    {
     "title": "Process - SSL cache",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_ssl_cache_lookups_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups"
      },
      {
       "expr": "rate(haproxy_process_ssl_cache_misses_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Miss"
      },
      {
       "expr": "rate(haproxy_process_ssl_connections_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "SSL Connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{instance=\"$host\"}",
       "legendFormat": "Frontend SSL connections which did not require a new key"
      }
     ]
    },
    {
     "title": "Process - Zlib (HTTP compression) memory limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Amount of memory currently used by HTTP compression"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Limit memory used by HTTP compression,  above is auto disabled (in bytes, see global.maxzlibmem)"
      }
     ]
    }
   ]
  }
 ]
}