{
 "title": "HAProxy / Status",
 "description": "HAProxy Status metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16209 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16209 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Server - Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16338 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Status other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16346 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\",state!~\"UP|DOWN\"}",
       "legendFormat": "{{ proxy }} / {{ server }} - {{state}}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16354 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_internal_errors_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16354 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16365 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Sticktable usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16372 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_sticktable_size{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      },
      {
       "expr": "haproxy_sticktable_used{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16372 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16383 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  }
 ]
}