{
 "title": "HAProxy / Times",
 "description": "HAProxy Times metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 720 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 727 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 748 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 755 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  }
 ]
}