{
 "title": "HAProxy / Sessions",
 "description": "HAProxy Sessions metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max_over_time(haproxy_frontend_current_sessions{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval]) / haproxy_frontend_limit_sessions{proxy=~\"$frontend\", instance=\"$host\"} * 100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max_over_time(haproxy_backend_current_sessions{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval]) / haproxy_backend_limit_sessions{proxy=~\"$backend\", instance=\"$host\"} * 100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session Max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_max_sessions{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_client_aborts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_server_aborts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  }
 ]
}