{
 "title": "HAProxy / Requests / Responses",
 "description": "HAProxy Requests / Responses metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP requests Total / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16203 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP requests Total / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16203 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_requests_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19191 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19191 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19204 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (proxy, server)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19212 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19212 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19225 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} - {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19248 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19257 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19271 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  }
 ]
}