{
 "title": "HAProxy / Throughput / Connections",
 "description": "HAProxy Throughput / Connections metrics",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Throughput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19193 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Connections Accepted / Denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 19200 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Accepted {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections Attempts / Errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19200 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempt {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections Attempts / Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19215 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19222 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19237 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  }
 ]
}