apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valkey-operator
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - valkey
    resources:
      - valkeyclusters
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - valkey
    resources:
      - valkeyclusters/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - valkey
    resources:
      - valkeyclusters/finalizers
    verbs:
      - update
