apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey-operator
  namespace: valkey-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: valkey-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: valkey-operator
subjects:
  - kind: ServiceAccount
    name: valkey-operator
    namespace: valkey-system
