apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - kube.yaml
configMapGenerator:
  - name: patroni-config
    files:
      - ./patroni.yaml
generatorOptions:
  disableNameSuffixHash: false # changes the suffix hash of names so services automatically reload
