apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-operator
  namespace: default
  labels:
    app.kubernetes.io/name: valkey-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey-operator
    spec:
      serviceAccountName: valkey-operator
      containers:
        - name: manager
          image: ghcr.io/pandoks/valkey-operator:latest
          args:
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          ports:
            - name: http-metrics
              containerPort: 8080
            - name: http-probe
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-probe
          readinessProbe:
            httpGet:
              path: /readyz
              port: http-probe
