apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-issuer
  namespace: main
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-root-ca
  namespace: main
spec:
  isCA: true
  commonName: internal-root-ca
  secretName: internal-root-ca-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: internal-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-ca-issuer
  namespace: main
spec:
  ca:
    secretName: internal-root-ca-secret
