apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: &name cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: *name
  version: v1.17.0
  targetNamespace: *name
  createNamespace: true
  valuesContent: |-
    installCRDs: true
