# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: handler.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 0, "", "handler.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rhandler.proto\x12\x1epandoks.queueworker.runtime.v1":\n\rHandleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61ttempt\x18\x03 \x01(\x05"\'\n\x0bPublication\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c"\x9c\x01\n\x0eHandleResponse\x12\x38\n\x07outcome\x18\x01 \x01(\x0e\x32\'.pandoks.queueworker.runtime.v1.Outcome\x12\x41\n\x0cpublications\x18\x02 \x03(\x0b\x32+.pandoks.queueworker.runtime.v1.Publication\x12\r\n\x05\x65rror\x18\x03 \x01(\t*_\n\x07Outcome\x12\x17\n\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n\x0fOUTCOME_SUCCESS\x10\x01\x12\x11\n\rOUTCOME_RETRY\x10\x02\x12\x13\n\x0fOUTCOME_DISCARD\x10\x03\x32r\n\x07Handler\x12g\n\x06Handle\x12-.pandoks.queueworker.runtime.v1.HandleRequest\x1a..pandoks.queueworker.runtime.v1.HandleResponseB"Z queueworker/runtime/v1;runtimev1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "handler_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z queueworker/runtime/v1;runtimev1"
    _globals["_OUTCOME"]._serialized_start = 309
    _globals["_OUTCOME"]._serialized_end = 404
    _globals["_HANDLEREQUEST"]._serialized_start = 49
    _globals["_HANDLEREQUEST"]._serialized_end = 107
    _globals["_PUBLICATION"]._serialized_start = 109
    _globals["_PUBLICATION"]._serialized_end = 148
    _globals["_HANDLERESPONSE"]._serialized_start = 151
    _globals["_HANDLERESPONSE"]._serialized_end = 307
    _globals["_HANDLER"]._serialized_start = 406
    _globals["_HANDLER"]._serialized_end = 520
# @@protoc_insertion_point(module_scope)
