apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main-clickhouse-main-cluster
  namespace: kube-system
spec:
  chart: oci://ghcr.io/pandoks/charts/clickhouse
  version: 0.1.0
  targetNamespace: &namespace main
  createNamespace: true
  failurePolicy: abort
  set:
    name: main
    namespace: *namespace
    credentials.secret: clickhouse-main-creds
    backup.bucket: dev-backups
    backup.path: /main/clickhouse
