// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: packages/queueworker/runtime/v1/handler.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCESS     Outcome = 1
	Outcome_OUTCOME_RETRY       Outcome = 2
	Outcome_OUTCOME_DISCARD     Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCESS",
		2: "OUTCOME_RETRY",
		3: "OUTCOME_DISCARD",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUCCESS":     1,
		"OUTCOME_RETRY":       2,
		"OUTCOME_DISCARD":     3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_packages_queueworker_runtime_v1_handler_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_packages_queueworker_runtime_v1_handler_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_packages_queueworker_runtime_v1_handler_proto_rawDescGZIP(), []int{0}
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_packages_queueworker_runtime_v1_handler_proto_rawDescGZIP(), []int{0}
}

func (x *HandleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HandleRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Publication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_packages_queueworker_runtime_v1_handler_proto_rawDescGZIP(), []int{1}
}

func (x *Publication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Publication) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       Outcome                `protobuf:"varint,1,opt,name=outcome,proto3,enum=pandoks.queueworker.runtime.v1.Outcome" json:"outcome,omitempty"`
	Publications  []*Publication         `protobuf:"bytes,2,rep,name=publications,proto3" json:"publications,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_queueworker_runtime_v1_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_packages_queueworker_runtime_v1_handler_proto_rawDescGZIP(), []int{2}
}

func (x *HandleResponse) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *HandleResponse) GetPublications() []*Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

func (x *HandleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_packages_queueworker_runtime_v1_handler_proto protoreflect.FileDescriptor

const file_packages_queueworker_runtime_v1_handler_proto_rawDesc = "" +
	"\n" +
	"-packages/queueworker/runtime/v1/handler.proto\x12\x1epandoks.queueworker.runtime.v1\"M\n" +
	"\rHandleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"1\n" +
	"\vPublication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\xba\x01\n" +
	"\x0eHandleResponse\x12A\n" +
	"\aoutcome\x18\x01 \x01(\x0e2'.pandoks.queueworker.runtime.v1.OutcomeR\aoutcome\x12O\n" +
	"\fpublications\x18\x02 \x03(\v2+.pandoks.queueworker.runtime.v1.PublicationR\fpublications\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*_\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_SUCCESS\x10\x01\x12\x11\n" +
	"\rOUTCOME_RETRY\x10\x02\x12\x13\n" +
	"\x0fOUTCOME_DISCARD\x10\x032r\n" +
	"\aHandler\x12g\n" +
	"\x06Handle\x12-.pandoks.queueworker.runtime.v1.HandleRequest\x1a..pandoks.queueworker.runtime.v1.HandleResponseB\"Z queueworker/runtime/v1;runtimev1b\x06proto3"

var (
	file_packages_queueworker_runtime_v1_handler_proto_rawDescOnce sync.Once
	file_packages_queueworker_runtime_v1_handler_proto_rawDescData []byte
)

func file_packages_queueworker_runtime_v1_handler_proto_rawDescGZIP() []byte {
	file_packages_queueworker_runtime_v1_handler_proto_rawDescOnce.Do(func() {
		file_packages_queueworker_runtime_v1_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_queueworker_runtime_v1_handler_proto_rawDesc), len(file_packages_queueworker_runtime_v1_handler_proto_rawDesc)))
	})
	return file_packages_queueworker_runtime_v1_handler_proto_rawDescData
}

var file_packages_queueworker_runtime_v1_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packages_queueworker_runtime_v1_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packages_queueworker_runtime_v1_handler_proto_goTypes = []any{
	(Outcome)(0),           // 0: pandoks.queueworker.runtime.v1.Outcome
	(*HandleRequest)(nil),  // 1: pandoks.queueworker.runtime.v1.HandleRequest
	(*Publication)(nil),    // 2: pandoks.queueworker.runtime.v1.Publication
	(*HandleResponse)(nil), // 3: pandoks.queueworker.runtime.v1.HandleResponse
}
var file_packages_queueworker_runtime_v1_handler_proto_depIdxs = []int32{
	0, // 0: pandoks.queueworker.runtime.v1.HandleResponse.outcome:type_name -> pandoks.queueworker.runtime.v1.Outcome
	2, // 1: pandoks.queueworker.runtime.v1.HandleResponse.publications:type_name -> pandoks.queueworker.runtime.v1.Publication
	1, // 2: pandoks.queueworker.runtime.v1.Handler.Handle:input_type -> pandoks.queueworker.runtime.v1.HandleRequest
	3, // 3: pandoks.queueworker.runtime.v1.Handler.Handle:output_type -> pandoks.queueworker.runtime.v1.HandleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_packages_queueworker_runtime_v1_handler_proto_init() }
func file_packages_queueworker_runtime_v1_handler_proto_init() {
	if File_packages_queueworker_runtime_v1_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_queueworker_runtime_v1_handler_proto_rawDesc), len(file_packages_queueworker_runtime_v1_handler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_queueworker_runtime_v1_handler_proto_goTypes,
		DependencyIndexes: file_packages_queueworker_runtime_v1_handler_proto_depIdxs,
		EnumInfos:         file_packages_queueworker_runtime_v1_handler_proto_enumTypes,
		MessageInfos:      file_packages_queueworker_runtime_v1_handler_proto_msgTypes,
	}.Build()
	File_packages_queueworker_runtime_v1_handler_proto = out.File
	file_packages_queueworker_runtime_v1_handler_proto_goTypes = nil
	file_packages_queueworker_runtime_v1_handler_proto_depIdxs = nil
}
