name: example
namespace: example

credentials:
  secret: clickhouse-example-creds
  dataKeys:
    adminPassword: ADMIN_PASSWORD
    clientPassword: CLIENT_PASSWORD

clickhouse:
  image: ghcr.io/pandoks/clickhouse:latest@sha256:9c3bdb4117812ac7a46e583754c18d63d4e78f7f3dfb700c453670047f9417c8
  shards: 1
  replicasPerShard: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4Gi

keeper:
  image: ghcr.io/pandoks/clickhouse-keeper:latest@sha256:58a7240eb649c6a91d40e8941a77f15501685c93ac345b678a98ccb9dca4fda3
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 4Gi

backup:
  credentials:
    secret: backup-bucket-creds
    dataKeys:
      accessKey: S3_ACCESS_KEY
      secretKey: S3_SECRET_KEY
  image: ghcr.io/pandoks/clickhouse-backup:latest@sha256:692e2dff2618e55c182ebbe4fa2a723a18a1603caf1252fc8ff7d739c3993ce1
  bucket: backups
  path: kubernetes/example/clickhouse
  schedules:
    full: '0 2 * * 0'
    diff: '0 2 * * 3,6'
    incr: '0 2 * * 1,2,4,5'
  retention:
    full: 3
    diff: 6
    incr: 24
  resources: {}

s3:
  region: us-west-1
  endpoint: http://host.k3d.internal:4566
