name: example
namespace: example

credentials:
  secret: clickhouse-example-creds
  dataKeys:
    adminPassword: ADMIN_PASSWORD
    clientPassword: CLIENT_PASSWORD

clickhouse:
  image: ghcr.io/pandoks/clickhouse:latest@sha256:374bc1bfc80f19b3b520588120762c6410304a4b25519e24371d3418bd809600
  shards: 1
  replicasPerShard: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4Gi

keeper:
  image: ghcr.io/pandoks/clickhouse-keeper:latest@sha256:8f643ffbb6403dc26a895a79db4527cb191ac29f787e2bfa732d414100036e08
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 4Gi

backup:
  credentials:
    secret: backup-bucket-creds
    dataKeys:
      accessKey: S3_ACCESS_KEY
      secretKey: S3_SECRET_KEY
  image: ghcr.io/pandoks/clickhouse-backup:latest@sha256:1cca776f647d20992503ba56e732386f7e14adc3c48d9d02be8ef64ce7ba412b
  bucket: backups
  path: kubernetes/example/clickhouse
  schedules:
    full: '0 2 * * 0'
    diff: '0 2 * * 3,6'
    incr: '0 2 * * 1,2,4,5'
  retention:
    full: 3
    diff: 6
    incr: 24
  resources: {}

s3:
  region: us-west-1
  endpoint: http://host.k3d.internal:4566
