apiVersion: v1
kind: Namespace
metadata:
  name: tailscale

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: kube-system
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  version: 1.92.4
  targetNamespace: tailscale
  valuesSecrets:
    - name: tailscale-oauth
      keys:
        - tailscale-oauth-yaml
