/**
 * NOTE: this file is used by both the infra and the apps/functions. we do this to avoid functions
 * importing SST specifics and causing type errors. this also allows up to sync up the instances
 * to gate.
 */
export const ARM_INSTANCE_TYPES = [
  'c7g.large',
  'c7g.xlarge',
  'c7g.2xlarge',
  'c7g.4xlarge',
  'c7g.8xlarge',
  'c7g.12xlarge',
  'c7g.16xlarge',
  'c8g.large',
  'c8g.xlarge',
  'c8g.2xlarge',
  'c8g.4xlarge',
  'c8g.8xlarge',
  'c8g.12xlarge',
  'c8g.16xlarge',
  'c8g.24xlarge',
  'c8g.48xlarge',
  'm7g.large',
  'm7g.xlarge',
  'm7g.2xlarge',
  'm7g.4xlarge',
  'm7g.8xlarge',
  'm7g.12xlarge',
  'm7g.16xlarge',
  'm8g.large',
  'm8g.xlarge',
  'm8g.2xlarge',
  'm8g.4xlarge',
  'm8g.8xlarge',
  'm8g.12xlarge',
  'm8g.16xlarge',
  'm8g.24xlarge',
  'm8g.48xlarge'
] as const;

export const X86_INSTANCE_TYPES = [
  'c7i.large',
  'c7i.xlarge',
  'c7i.2xlarge',
  'c7i.4xlarge',
  'c7i.8xlarge',
  'c7i.12xlarge',
  'c7i.16xlarge',
  'c7i.24xlarge',
  'c7i.48xlarge',
  'c7i.metal-24xl',
  'c7i.metal-48xl',
  'c8i.large',
  'c8i.xlarge',
  'c8i.2xlarge',
  'c8i.4xlarge',
  'c8i.8xlarge',
  'c8i.12xlarge',
  'c8i.16xlarge',
  'c8i.24xlarge',
  'c8i.48xlarge',
  'c8i.metal-24xl',
  'c8i.metal-48xl',
  'c8a.large',
  'c8a.xlarge',
  'c8a.2xlarge',
  'c8a.4xlarge',
  'c8a.8xlarge',
  'c8a.12xlarge',
  'c8a.16xlarge',
  'c8a.24xlarge',
  'c8a.48xlarge',
  'm7i.large',
  'm7i.xlarge',
  'm7i.2xlarge',
  'm7i.4xlarge',
  'm7i.8xlarge',
  'm7i.12xlarge',
  'm7i.16xlarge',
  'm7i.24xlarge',
  'm7i.48xlarge',
  'm8i.large',
  'm8i.xlarge',
  'm8i.2xlarge',
  'm8i.4xlarge',
  'm8i.8xlarge',
  'm8i.12xlarge',
  'm8i.16xlarge',
  'm8i.24xlarge',
  'm8i.48xlarge',
  'm8i.metal-24xl',
  'm8i.metal-48xl'
] as const;

export const SUPPORTED_INSTANCE_TYPES = [...ARM_INSTANCE_TYPES, ...X86_INSTANCE_TYPES] as const;

export type InstanceType = (typeof SUPPORTED_INSTANCE_TYPES)[number];
