apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - patroni-role.yaml

helmGlobals:
  chartHome: ../charts
helmCharts:
  - name: db
    releaseName: main-postgres
    namespace: main
    valuesFile: ./main/postgres.yaml
  - name: backup
    releaseName: main-pgbackrest-backup-full
    namespace: main
    valuesFile: ./main/full-backup.yaml
  - name: backup
    releaseName: main-pgbackrest-backup-diff
    namespace: main
    valuesFile: ./main/diff-backup.yaml
  - name: backup
    releaseName: main-pgbackrest-backup-incr
    namespace: main
    valuesFile: ./main/incr-backup.yaml

configMapGenerator:
  - name: pgcat-config
    files:
      - ../pgcat/pgcat.toml
  - name: patroni-config
    files:
      - ../patroni/patroni.yaml
  - name: patroni-pgbackrest-config
    files:
      - ../patroni/pgbackrest.conf
  - name: pgbackrest-server-config
    files:
      - ../pgbackrest/pgbackrest.conf

generatorOptions:
  disableNameSuffixHash: false # changes the suffix hash of names so services automatically reload
