apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni
  namespace: main

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patroni
  namespace: main
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
      - deletecollection
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
      - deletecollection
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &name patroni
  namespace: main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: *name
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: main
