name: Deploy pandoks.com
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'SST stage'
        required: true
        type: choice
        options:
          - production
          - pandoks

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter web --filter svelte

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::343487555569:role/PersonalGithubActions
          aws-region: us-west-1

      - name: Deploy pandoks.com
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
        run: pnpx sst deploy --stage ${{ github.event.inputs.stage }} --target StaticWebsite
